[general]
import = [ "~/.cache/wal/colors-alacritty.toml" ]
live_config_reload = true

[window]
opacity = 0.95
dynamic_title = true
decorations = "full"
padding = { x = 8, y = 8 }
dynamic_padding = true

[font]
normal= {family = "0xProto Nerd Font Mono", style = "Regular"}
size = 13.0
offset = {y = 6, x = 0}

[scrolling]
history = 10000
multiplier = 4
