shadow = true;

fading = true;
fade-in-step = 0.07;
fade-out-step = 0.07;

frame-opacity = 1;

corner-radius = 0;

blur-method = "dual_kawase"        # CPU blur
blur-size = 6                 # tweak, lower = faster, higher = stronger
blur-background = true         # only blur background, not window content
blur-background-fixed = true   # blur static background, better perf

backend = "xrender"
dithered-present = false;
vsync = true;
detect-rounded-corners = true;
detect-client-opacity = true;
use-damage = false;

shadow-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'Rofi'",
]
