[colors]
background = '#140e208e'
black = '#140e20'
blue = '#837B69'
cursor = '#c4c2c7'
cyan = '#768E65'
foreground = '#c4c2c7'
green = '#739765'
magenta = '#8AA174'
red = '#8FC17E'
tabs = '#c4c2c7'
tabs-active = '#A4AF8F'
white = '#c4c2c7'
yellow = '#c4c2c7'
dim-black = '#140e208e'
dim-blue = '#837B698e'
dim-cyan = '#768E658e'
dim-foreground = '#c4c2c78e'
dim-green = '#7397658e'
dim-magenta = '#8AA1748e'
dim-red = '#8FC17E8e'
dim-white = '#A4AF8F8e'
dim-yellow = '#c4c2c78e'
light-black = '#837B69'
light-blue = '#768E65'
light-cyan = '#739765'
light-foreground = '#8AA174'
light-green = '#8FC17E'
light-magenta = '#A4AF8F'
light-red = '#c4c2c7'
light-white = '#837B69'
light-yellow = '#768E65'
