--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mcreinii/Wallpapers/#14.png"

-- Special
background="#0b0b1a"
foreground="#c2c2c5"
cursor="#c2c2c5"

-- Colors
color0="#0b0b1a"
color1="#686D94"
color2="#686D95"
color3="#7D83B1"
color4="#838AB9"
color5="#949BD1"
color6="#B4BDFD"
color7="#c2c2c5"
color8="#5a5a6f"
color9="#686D94"
color10="#686D95"
color11="#7D83B1"
color12="#838AB9"
color13="#949BD1"
color14="#B4BDFD"
color15="#c2c2c5"
