[colors.primary]
background = "#140e20"
foreground = "#c4c2c7"

[colors.cursor]
text = "#140e20"
cursor = "#c4c2c7"

[colors.vi_mode_cursor]
text = "#140e20"
cursor = "#c4c2c7"

[colors.search.matches]
foreground = "#140e20"
background = "#c4c2c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#645d72"
background = "#c4c2c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#140e20"
red = "#837B69"
green = "#768E65"
yellow = "#739765"
blue = "#8AA174"
magenta = "#8FC17E"
cyan = "#A4AF8F"
white = "#c4c2c7"

[colors.bright]
black = "#645d72"
red = "#837B69"
green = "#768E65"
yellow = "#739765"
blue = "#8AA174"
magenta = "#8FC17E"
cyan = "#A4AF8F"
white = "#c4c2c7"

[colors.dim]
black = "#c4c2c7"
red = "#837B69"
green = "#8FC17E"
yellow = "#739765"
blue = "#8AA174"
magenta = "#768E65"
cyan = "#A4AF8F"
white = "#645d72"

