[colors]
background = '#1709098e'
black = '#170909'
blue = '#C15846'
cursor = '#c5c1c1'
cyan = '#BB8566'
foreground = '#c5c1c1'
green = '#DB9572'
magenta = '#BA7784'
red = '#F0AD9D'
tabs = '#c5c1c1'
tabs-active = '#F1B191'
white = '#c5c1c1'
yellow = '#c5c1c1'
dim-black = '#1709098e'
dim-blue = '#C158468e'
dim-cyan = '#BB85668e'
dim-foreground = '#c5c1c18e'
dim-green = '#DB95728e'
dim-magenta = '#BA77848e'
dim-red = '#F0AD9D8e'
dim-white = '#F1B1918e'
dim-yellow = '#c5c1c18e'
light-black = '#C15846'
light-blue = '#BB8566'
light-cyan = '#DB9572'
light-foreground = '#BA7784'
light-green = '#F0AD9D'
light-magenta = '#F1B191'
light-red = '#c5c1c1'
light-white = '#C15846'
light-yellow = '#BB8566'
