foreground         #c4cbcc
background         #162f33
background_opacity 1.0
cursor             #c4cbcc

active_tab_foreground     #162f33
active_tab_background     #c4cbcc
inactive_tab_foreground   #c4cbcc
inactive_tab_background   #162f33

active_border_color   #c4cbcc
inactive_border_color #162f33
bell_border_color     #4A7888

color0       #162f33
color8       #65787b
color1       #4A7888
color9       #4A7888
color2       #5A9298
color10      #5A9298
color3       #4C96AD
color11      #4C96AD
color4       #76CDDC
color12      #76CDDC
color5       #78C7E2
color13      #78C7E2
color6       #9BAE9F
color14      #9BAE9F
color7       #c4cbcc
color15      #c4cbcc
