# Shell variables
# Generated by 'wal'
wallpaper="/home/mcreinii/Wallpapers/#02.png"

# Special
background='#170909'
foreground='#c5c1c1'
cursor='#c5c1c1'

# Colors
color0='#170909'
color1='#C15846'
color2='#BB8566'
color3='#DB9572'
color4='#BA7784'
color5='#F0AD9D'
color6='#F1B191'
color7='#c5c1c1'
color8='#6d5959'
color9='#C15846'
color10='#BB8566'
color11='#DB9572'
color12='#BA7784'
color13='#F0AD9D'
color14='#F1B191'
color15='#c5c1c1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
