# Shell variables
# Generated by 'wal'
wallpaper="/home/mcreinii/Wallpapers/#03.png"

# Special
background='#101010'
foreground='#c3c3c3'
cursor='#c3c3c3'

# Colors
color0='#101010'
color1='#586DAE'
color2='#647AB6'
color3='#6376D1'
color4='#6981BC'
color5='#6E88CE'
color6='#7891E2'
color7='#c3c3c3'
color8='#6c5959'
color9='#586DAE'
color10='#647AB6'
color11='#6376D1'
color12='#6981BC'
color13='#6E88CE'
color14='#7891E2'
color15='#c3c3c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
