foreground         #c2c2c5
background         #0b0b1a
background_opacity 1.0
cursor             #c2c2c5

active_tab_foreground     #0b0b1a
active_tab_background     #c2c2c5
inactive_tab_foreground   #c2c2c5
inactive_tab_background   #0b0b1a

active_border_color   #c2c2c5
inactive_border_color #0b0b1a
bell_border_color     #686D94

color0       #0b0b1a
color8       #5a5a6f
color1       #686D94
color9       #686D94
color2       #686D95
color10      #686D95
color3       #7D83B1
color11      #7D83B1
color4       #838AB9
color12      #838AB9
color5       #949BD1
color13      #949BD1
color6       #B4BDFD
color14      #B4BDFD
color7       #c2c2c5
color15      #c2c2c5
