[colors]
background = '#1010108e'
black = '#101010'
blue = '#586DAE'
cursor = '#c3c3c3'
cyan = '#647AB6'
foreground = '#c3c3c3'
green = '#6376D1'
magenta = '#6981BC'
red = '#6E88CE'
tabs = '#c3c3c3'
tabs-active = '#7891E2'
white = '#c3c3c3'
yellow = '#c3c3c3'
dim-black = '#1010108e'
dim-blue = '#586DAE8e'
dim-cyan = '#647AB68e'
dim-foreground = '#c3c3c38e'
dim-green = '#6376D18e'
dim-magenta = '#6981BC8e'
dim-red = '#6E88CE8e'
dim-white = '#7891E28e'
dim-yellow = '#c3c3c38e'
light-black = '#586DAE'
light-blue = '#647AB6'
light-cyan = '#6376D1'
light-foreground = '#6981BC'
light-green = '#6E88CE'
light-magenta = '#7891E2'
light-red = '#c3c3c3'
light-white = '#586DAE'
light-yellow = '#647AB6'
