# Shell variables
# Generated by 'wal'
wallpaper="/home/mcreinii/Wallpapers/#14.png"

# Special
background='#0b0b1a'
foreground='#c2c2c5'
cursor='#c2c2c5'

# Colors
color0='#0b0b1a'
color1='#686D94'
color2='#686D95'
color3='#7D83B1'
color4='#838AB9'
color5='#949BD1'
color6='#B4BDFD'
color7='#c2c2c5'
color8='#5a5a6f'
color9='#686D94'
color10='#686D95'
color11='#7D83B1'
color12='#838AB9'
color13='#949BD1'
color14='#B4BDFD'
color15='#c2c2c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
