--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mcreinii/Wallpapers/#02.png"

-- Special
background="#170909"
foreground="#c5c1c1"
cursor="#c5c1c1"

-- Colors
color0="#170909"
color1="#C15846"
color2="#BB8566"
color3="#DB9572"
color4="#BA7784"
color5="#F0AD9D"
color6="#F1B191"
color7="#c5c1c1"
color8="#6d5959"
color9="#C15846"
color10="#BB8566"
color11="#DB9572"
color12="#BA7784"
color13="#F0AD9D"
color14="#F1B191"
color15="#c5c1c1"
