foreground         #c5c1c1
background         #170909
background_opacity 1.0
cursor             #c5c1c1

active_tab_foreground     #170909
active_tab_background     #c5c1c1
inactive_tab_foreground   #c5c1c1
inactive_tab_background   #170909

active_border_color   #c5c1c1
inactive_border_color #170909
bell_border_color     #C15846

color0       #170909
color8       #6d5959
color1       #C15846
color9       #C15846
color2       #BB8566
color10      #BB8566
color3       #DB9572
color11      #DB9572
color4       #BA7784
color12      #BA7784
color5       #F0AD9D
color13      #F0AD9D
color6       #F1B191
color14      #F1B191
color7       #c5c1c1
color15      #c5c1c1
