--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mcreinii/Wallpapers/134233-1253848273.jpg"

-- Special
background="#162f33"
foreground="#c4cbcc"
cursor="#c4cbcc"

-- Colors
color0="#162f33"
color1="#4A7888"
color2="#5A9298"
color3="#4C96AD"
color4="#76CDDC"
color5="#78C7E2"
color6="#9BAE9F"
color7="#c4cbcc"
color8="#65787b"
color9="#4A7888"
color10="#5A9298"
color11="#4C96AD"
color12="#76CDDC"
color13="#78C7E2"
color14="#9BAE9F"
color15="#c4cbcc"
