[colors.primary]
background = "#0b0b1a"
foreground = "#c2c2c5"

[colors.cursor]
text = "#0b0b1a"
cursor = "#c2c2c5"

[colors.vi_mode_cursor]
text = "#0b0b1a"
cursor = "#c2c2c5"

[colors.search.matches]
foreground = "#0b0b1a"
background = "#c2c2c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5a5a6f"
background = "#c2c2c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0b0b1a"
red = "#686D94"
green = "#686D95"
yellow = "#7D83B1"
blue = "#838AB9"
magenta = "#949BD1"
cyan = "#B4BDFD"
white = "#c2c2c5"

[colors.bright]
black = "#5a5a6f"
red = "#686D94"
green = "#686D95"
yellow = "#7D83B1"
blue = "#838AB9"
magenta = "#949BD1"
cyan = "#B4BDFD"
white = "#c2c2c5"

[colors.dim]
black = "#c2c2c5"
red = "#686D94"
green = "#949BD1"
yellow = "#7D83B1"
blue = "#838AB9"
magenta = "#686D95"
cyan = "#B4BDFD"
white = "#5a5a6f"

