[colors.primary]
background = "#170909"
foreground = "#c5c1c1"

[colors.cursor]
text = "#170909"
cursor = "#c5c1c1"

[colors.vi_mode_cursor]
text = "#170909"
cursor = "#c5c1c1"

[colors.search.matches]
foreground = "#170909"
background = "#c5c1c1"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6d5959"
background = "#c5c1c1"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#170909"
red = "#C15846"
green = "#BB8566"
yellow = "#DB9572"
blue = "#BA7784"
magenta = "#F0AD9D"
cyan = "#F1B191"
white = "#c5c1c1"

[colors.bright]
black = "#6d5959"
red = "#C15846"
green = "#BB8566"
yellow = "#DB9572"
blue = "#BA7784"
magenta = "#F0AD9D"
cyan = "#F1B191"
white = "#c5c1c1"

[colors.dim]
black = "#c5c1c1"
red = "#C15846"
green = "#F0AD9D"
yellow = "#DB9572"
blue = "#BA7784"
magenta = "#BB8566"
cyan = "#F1B191"
white = "#6d5959"

