# pywal theme for ghostty

background = 21250f
foreground = c7c8c3
cursor-color = c7c8c3
selection-background = c7c8c3
selection-foreground = 21250f

palette = 0=#21250f
palette = 1=#7F945C
palette = 2=#6B9064
palette = 3=#99933E
palette = 4=#9DA65E
palette = 5=#CCB755
palette = 6=#E5CC6E
palette = 7=#c7c8c3
palette = 8=#70745f
palette = 9=#7F945C
palette = 10=#6B9064
palette = 11=#99933E
palette = 12=#9DA65E
palette = 13=#CCB755
palette = 14=#E5CC6E
palette = 15=#c7c8c3
