# pywal theme for ghostty

background = 140e20
foreground = c4c2c7
cursor-color = c4c2c7
selection-background = c4c2c7
selection-foreground = 140e20

palette = 0=#140e20
palette = 1=#837B69
palette = 2=#768E65
palette = 3=#739765
palette = 4=#8AA174
palette = 5=#8FC17E
palette = 6=#A4AF8F
palette = 7=#c4c2c7
palette = 8=#645d72
palette = 9=#837B69
palette = 10=#768E65
palette = 11=#739765
palette = 12=#8AA174
palette = 13=#8FC17E
palette = 14=#A4AF8F
palette = 15=#c4c2c7
