# pywal theme for ghostty

background = 0b0b1a
foreground = c2c2c5
cursor-color = c2c2c5
selection-background = c2c2c5
selection-foreground = 0b0b1a

palette = 0=#0b0b1a
palette = 1=#686D94
palette = 2=#686D95
palette = 3=#7D83B1
palette = 4=#838AB9
palette = 5=#949BD1
palette = 6=#B4BDFD
palette = 7=#c2c2c5
palette = 8=#5a5a6f
palette = 9=#686D94
palette = 10=#686D95
palette = 11=#7D83B1
palette = 12=#838AB9
palette = 13=#949BD1
palette = 14=#B4BDFD
palette = 15=#c2c2c5
